# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Glitchd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install backend dependencies
        run: |
          npm install

      - name: Build frontend (if exists)
        run: |
          if [ -d "frontend" ]; then
            echo "Frontend directory found, building frontend..."
            cd frontend
            npm install
            
            # Update browserslist database to remove warnings
            npx update-browserslist-db@latest || true
            
            # Build with CI=false to treat warnings as warnings, not errors
            CI=false GENERATE_SOURCEMAP=false npm run build
            cd ..
          else
            echo "No frontend directory found, skipping frontend build"
          fi

      - name: Create deployment package
        run: |
          echo "Creating deployment package..."
          
          # Create a clean directory structure
          mkdir -p deploy-package
          
          # Copy backend files
          cp package.json deploy-package/
          cp server.js deploy-package/
          cp -r routes deploy-package/ 2>/dev/null || echo "No routes directory"
          cp -r middleware deploy-package/ 2>/dev/null || echo "No middleware directory"
          cp -r models deploy-package/ 2>/dev/null || echo "No models directory"
          cp -r config deploy-package/ 2>/dev/null || echo "No config directory"
          cp -r utils deploy-package/ 2>/dev/null || echo "No utils directory"
          cp web.config deploy-package/ 2>/dev/null || echo "No web.config file"
          
          # Copy frontend build if it exists
          if [ -d "frontend/build" ]; then
            echo "Copying frontend build..."
            cp -r frontend/build deploy-package/
          fi
          
          # Move deployment package contents to current directory
          cp -r deploy-package/* .
          rm -rf deploy-package

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !node_modules
            !frontend
            !.git
            !.github

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_588E826937B9452A8843CE8946E91B7E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1E2F94C8CA45491C8BEB62F84662ADD2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_93B1839BC9BC42F5915464CB0BCAE9E5 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Glitchd'
          slot-name: 'Production'
          package: .
          startup-command: 'npm start'